///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package PL_X_cms_subsystem_0_0_s_axi_ctrl_pkg;
import axi_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_PROTOCOL           = 2;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_READ_WRITE_MODE    = "READ_WRITE";
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_INTERFACE_MODE     = 1;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ADDR_WIDTH         = 18;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_DATA_WIDTH         = 32;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ID_WIDTH           = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_AWUSER_WIDTH       = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ARUSER_WIDTH       = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_RUSER_WIDTH        = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_WUSER_WIDTH        = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_BUSER_WIDTH        = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_SUPPORTS_NARROW    = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_BURST          = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_LOCK           = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_CACHE          = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_REGION         = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_QOS            = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_PROT           = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_WSTRB          = 1;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_BRESP          = 1;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_RRESP          = 1;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_ACLKEN         = 0;
      parameter PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_ARESETN        = 1;
///////////////////////////////////////////////////////////////////////////

typedef axi_passthrough_agent #(PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_PROTOCOL, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ADDR_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_DATA_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_DATA_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ID_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ID_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_AWUSER_WIDTH, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_WUSER_WIDTH, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_BUSER_WIDTH, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ARUSER_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_RUSER_WIDTH, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_SUPPORTS_NARROW, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_BURST,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_LOCK,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_CACHE,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_REGION,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_PROT,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_QOS,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_WSTRB,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_BRESP,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_RRESP,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_ARESETN) PL_X_cms_subsystem_0_0_s_axi_ctrl_passthrough_t;

typedef axi_passthrough_mem_agent #(PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_PROTOCOL, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ADDR_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_DATA_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_DATA_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ID_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ID_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_AWUSER_WIDTH, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_WUSER_WIDTH, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_BUSER_WIDTH, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_ARUSER_WIDTH,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_RUSER_WIDTH, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_SUPPORTS_NARROW, 
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_BURST,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_LOCK,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_CACHE,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_REGION,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_PROT,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_QOS,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_WSTRB,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_BRESP,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_RRESP,
                                PL_X_cms_subsystem_0_0_s_axi_ctrl_VIP_HAS_ARESETN) PL_X_cms_subsystem_0_0_s_axi_ctrl_passthrough_mem_t;

///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      PL_X_cms_subsystem_0_0_s_axi_ctrl_passthrough_t  PL_X_cms_subsystem_0_0_s_axi_ctrl_passthrough;
//      initial begin : START_PL_X_cms_subsystem_0_0_s_axi_ctrl_SLAVE
//        PL_X_cms_subsystem_0_0_s_axi_ctrl_passthrough = new("PL_X_cms_subsystem_0_0_s_axi_ctrl_passthrough", `PL_X_cms_subsystem_0_0_s_axi_ctrl_PATH_TO_INTERFACE);
//        PL_X_cms_subsystem_0_0_s_axi_ctrl_passthrough.start_master(); //passthrough in run time master mode
//        PL_X_cms_subsystem_0_0_s_axi_ctrl_passthrough.start_slave(); //passthrough in run time slave mode
//      end


endpackage : PL_X_cms_subsystem_0_0_s_axi_ctrl_pkg
